site_name: WebFramework
site_url: https://web-framework.com
site_author: Avoutic
site_description: >-
  Quickly build PHP applications with Slim Framework and PHP-DI, without a
  framework like Laravel of Symfony.

repo_name: avoutic/web-framework
repo_url: https://github.com/avoutic/web-framework

copyright: Copyright &copy; 2024 Avoutic

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/avoutic/web-framework
    - icon: fontawesome/brands/php
      link: https://packagist.org/packages/avoutic/web-framework

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Core Concepts:
    - entities-and-repositories.md
    - configuration.md
    - dependency-injection.md
    - new-entity.md
  - Request Handling:
    - routing.md
    - middlewares.md
    - emitting-responses.md
    - input-validation.md
    - templating.md
  - Database:
    - database.md
    - database-migrations.md
    - caching.md
  - Additional Features:
    - instrumentation.md
    - translations.md
    - sanity-checks.md
    - tasks.md
